name: Zip Root Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_go:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: go build

  zip_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a ZIP file containing all files in the root directory
      - name: Create ZIP file
        run: |
          echo "Creating ZIP file..."
          make prep
          mkdir -p /tmp/gearcore
          rsync -a --exclude={'*.png','*.ico','*.ini','*.manifest','.gitignore','*.bat','*.syso','*.md','Makefile'} . /tmp/gearcore
          cd /tmp
          zip -r gearcore.zip gearcore
          mv gearcore.zip $GITHUB_WORKSPACE/gearcore.zip

      # Upload the ZIP file as an artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: gearcore
          path: gearcore.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "GearCore UI"
          files: |
            gearcore.zip
